CREATE TABLE GENIE(
	NUM INT PRIMARY KEY, --PK
	NAME VARCHAR(800) NOT NULL, -- 노래 제목
	ARTIST VARCHAR(300) DEFAULT NULL, -- 가수 이름
	ALBUM VARCHAR(500) DEFAULT NULL  -- 앨범 이름
);
SELECT * FROM GENIE;	-- 노래목록 전체 출력


INSERT INTO GENIE VALUES((SELECT NVL(MAX(GID),0)+1 FROM GENIE));


DROP TABLE GENIE;	-- 테이블 삭제




CREATE TABLE ADMIN( -- 로그인 관련 테이블
	AID VARCHAR(20) PRIMARY KEY, -- 관리자의 아이디는 pk값으로1
	APW VARCHAR(20) NOT NULL, -- 관리자의 비밀번호는 null값일 수 없다
	ANAME VARCHAR(20) NOT NULL -- 관리자 이름도 마찬가지~
);
INSERT INTO ADMIN VALUES('coco','0607','관리자');

SELECT * FROM ADMIN;