SELECT * FROM USER_TABLES;
--DROP TABLE STUDENT; --STUDENT라는 테이블을 제거

-- CREATE, DROP 을 DDL이라고 부름
-- INSERT, SELECT, UPDATE, DELETE을 DDL이라고 부름

-- MySQL
-- SHOW DATABASES;
-- USE KIMDB;
-- SHOW TABLES;

CREATE
DROP
-- DDL

INSERT
SELECT
UPDATE
DELETE
-- DML

CREATE TABLE TEST1(
   NUM INT PRIMARY KEY,
   NAME VARCHAR(20) NOT NULL
);
-- 카테고리
-- EX) 소주,맥주,와인,... / 빵,야채,치즈,...
INSERT INTO TEST1 VALUES(101,'신발');
 -- 구두
 -- 운동화
 -- 슬리퍼
INSERT INTO TEST1 VALUES(102,'가방');
INSERT INTO TEST1 VALUES(103,'음료');
INSERT INTO TEST1 VALUES(104,'밀키트');
SELECT * FROM TEST1;

CREATE TABLE TEST2(
   PNUM INT PRIMARY KEY,	-- pk값
   PNAME VARCHAR(20) NOT NULL,
   NUM INT -- FK -- 다른 테이블의 PK정보를 자신 테이블에서 일반 컬럼으로 이용하는 경우
);
 -- 외래키(FK,FOREIGN KEY)
INSERT INTO TEST2 VALUES(11,'운동화',101);
SELECT * FROM TEST2;	-- 이퀄 조인

+++++

CREATE TABLE MEMBER(
   MID VARCHAR(20) PRIMARY KEY,
   MPW VARCHAR(20) NOT NULL,
   MNAME VARCHAR(20) NOT NULL
);
INSERT INTO MEMBER VALUES('ADMIN','1234','관리자');
SELECT * FROM MEMBER;

CREATE TABLE PRODUCT(
   PID INT PRIMARY KEY,
   PNAME VARCHAR(20) NOT NULL,
   CNT INT,
   PRICE INT
);
INSERT INTO PRODUCT VALUES(101,'운동화',2,29000);
INSERT INTO PRODUCT VALUES(102,'장편소설',10,35000);
SELECT * FROM PRODUCT;

